language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install codecov
    - python setup.py install
script:
    - pytest --cov=./pyad/
after_success:
    - codecov
